import Head from "next/head";
import React, { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import { getWordlist } from "utils/words";

export const getServerSideProps = async () => {
  const listofWords = getWordlist();
  const randWord = listofWords[Math.floor(Math.random() * listofWords.length)];

  return {
    props: {
      randWord,
    },
  };
};

//here is a comment to show how git works


export default function Home({ randWord }) {

  const [randHello, setRandHello] = useState('Hello World');

  function randomHello() {
    const listofHellos = [
     "Afrikaans:    Hello Wêreld!",
      "Albanian:     Përshendetje Botë!",
      "Amharic:      ሰላም ልዑል!",
      "Arabic:       مرحبا بالعالم!",
      "Armenian:     Բարեւ աշխարհ!",
      "Basque:       Kaixo Mundua!",
      "Belarussian:  Прывітанне Сусвет!",
      "Bengali:      ওহে বিশ্ব!",
      "Bulgarian:    Здравей свят!",
      "Catalan:      Hola món!",
      "Chichewa:     Moni Dziko Lapansi!",
      "Chinese:      你好世界",
      "Croatian:     Pozdrav svijete!",
      "Czech:        Ahoj světe!",
      "Danish:       Hej Verden!",
      "Dutch:        Hallo Wereld!",
      "English:      Hello World!",
      "Estonian:     Tere maailm!",
      "Finnish:      Hei maailma!",
      "French:       Bonjour monde!",
      "Frisian:      Hallo wrâld!",
      "Georgian:     გამარჯობა მსოფლიო!",
      "German:       Hallo Welt!",
      "Greek:        Γειά σου Κόσμε!",
      "Hausa:        Sannu Duniya!",
      "Hebrew:       שלום עולם!",
      "Hindi:        नमस्ते दुनिया!",
      "Hungarian:    Helló Világ!",
      "Icelandic:    Halló heimur!",
      "Igbo:         Ndewo Ụwa!",
      "Indonesian:   Halo Dunia!",
      "Italian:      Ciao mondo!",
      "Japanese:     こんにちは世界!",
      "Kazakh:       Сәлем Әлем!",
      "Khmer:        សួស្តី​ពិភពលោក!",
      "Kyrgyz:       Салам дүйнө!",
      "Lao:          ສະ​ບາຍ​ດີ​ຊາວ​ໂລກ!",
      "Latvian:      Sveika pasaule!",
      "Lithuanian:   Labas pasauli!",
      "Luxemburgish: Moien Welt!",
      "Macedonian:   Здраво свету!",
      "Malay:        Hai dunia!",
      "Malayalam:    ഹലോ വേൾഡ്!",
      "Mongolian:    Сайн уу дэлхий!",
      "Myanmar:      မင်္ဂလာပါကမ္ဘာလောက!",
      "Nepali:       नमस्कार संसार!",
      "Norwegian:    Hei Verden!",
      "Pashto:       سلام نړی!",
      "Persian:      سلام دنیا!",
      "Polish:       Witaj świecie!",
      "Portuguese:   Olá Mundo!",
      "Punjabi:      ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ ਦੁਨਿਆ!",
      "Romanian:     Salut Lume!",
      "Russian:      Привет мир!",
      "Scots Gaelic: Hàlo a Shaoghail!",
      "Serbian:      Здраво Свете!",
      "Sesotho:      Lefatše Lumela!",
      "Sinhala:      හෙලෝ වර්ල්ඩ්!",
      "Slovenian:    Pozdravljen svet!",
      "Spanish:      ¡Hola Mundo!",         // Leading '¡' optional
      "Sundanese:    Halo Dunya!",
      "Swahili:      Salamu Dunia!",
      "Swedish:      Hej världen!",
      "Tajik:        Салом Ҷаҳон!",
      "Thai:         สวัสดีชาวโลก!",
      "Turkish:      Selam Dünya!",
      "Ukrainian:    Привіт Світ!",
      "Uzbek:        Salom Dunyo!",
      "Vietnamese:   Chào thế giới!",
      "Welsh:        Helo Byd!",
      "Xhosa:        Molo Lizwe!",
      "Yiddish:      העלא וועלט!",
      "Yoruba:       Mo ki O Ile Aiye!",
      "Zulu:         Sawubona Mhlaba!",
    ];


    return listofHellos[Math.floor(Math.random() * listofHellos.length)];
  }

  const handleClick = () => {
    setRandHello(randomHello());
  }


  

  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Well Hello <a href="https://wordleunlimited.org/">There</a>
        </h1>

        <br />
        <p className={styles.description}>
          Here is a random {" "}
          <code className={styles.code}>Hello World</code>
          in multiple languages.
        </p>
        <br />
        <p className={styles.description}>
          <button className={styles.main} onClick={handleClick}>
            <code className={styles.code}>{randHello}</code>
          </button>
        </p>
      </main>
    </div>
  );
}
